### ISSUE TITLE
Vcpkg evpp v0.6.1 build fail with updated rapidjson 1.1.0

### ISSUE THREAD

**Issue by tristonl** [Qihoo360/evpp#139]
When I install evpp with "vcpkg install evpp" it fails with build error if i already have rapidjson 1.1.0 installed.
Install only successfull if I "vcpkg remove rapidjson", then install evpp again.

In the err log it seems the install is building with vcpkg version of rapidjson 1.1.0  if it's installed and not evpp's rapidjson 1.0.2 in evpp/3rdparty/rapidjson. So when I remove vcpkg's rapidjson it uses 3rdparty/rapidjson and then builds successfully.

Upgrading evpp's rapidjson to 1.1.0 should fix it. Or update evpp to use the 1.1.0 from vcpkg as a dep.

Here's my log from \vcpkg\buildtrees\evpp\install-x86-windows-dbg-out.log
         C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\src\evpp-0.6.1\apps\evnsq\option.cc(24): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'rapidjson::Value' [C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\x86-windows-dbg\apps\evnsq\evnsq_static.vcxproj]
         C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\src\evpp-0.6.1\apps\evnsq\option.cc(24): error C2661: 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::AddMember': no overloaded function takes 2 arguments [C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\x86-windows-dbg\apps\evnsq\evnsq_static.vcxproj]
         C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\src\evpp-0.6.1\apps\evnsq\option.cc(25): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'rapidjson::Value' [C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\x86-windows-dbg\apps\evnsq\evnsq_static.vcxproj]
         C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\src\evpp-0.6.1\apps\evnsq\option.cc(25): error C2661: 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::AddMember': no overloaded function takes 2 arguments [C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\x86-windows-dbg\apps\evnsq\evnsq_static.vcxproj]
         C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\src\evpp-0.6.1\apps\evnsq\option.cc(26): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'rapidjson::Value' [C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\x86-windows-dbg\apps\evnsq\evnsq_static.vcxproj]
         C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\src\evpp-0.6.1\apps\evnsq\option.cc(26): error C2661: 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::AddMember': no overloaded function takes 2 arguments [C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\x86-windows-dbg\apps\evnsq\evnsq_static.vcxproj]
         C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\src\evpp-0.6.1\apps\evnsq\option.cc(31): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'rapidjson::Value' [C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\x86-windows-dbg\apps\evnsq\evnsq_static.vcxproj]
         C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\src\evpp-0.6.1\apps\evnsq\option.cc(31): error C2661: 'rapidjson::GenericValue<rapidjson::UTF8<char>,rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator>>::AddMember': no overloaded function takes 2 arguments [C:\Users\master\WDATA\Software\Development\C++\Tools\Vcpkg\vcpkg\buildtrees\evpp\x86-windows-dbg\apps\evnsq\evnsq_static.vcxproj]

    22 Warning(s)
    8 Error(s)

Time Elapsed 00:04:13.04

**Comment by tristonl** [comment]
This change in CMakeLists fixes the build in v0.6.1:

else (UNIX)
set (CXX_FLAGS -DWIN32 -D_WIN32 -EHsc)
    set(VcpkgRoot ${_VCPKG_INSTALLED_DIR}/${VCPKG_TARGET_TRIPLET})
    include_directories(${PROJECT_SOURCE_DIR} **${PROJECT_SOURCE_DIR}/3rdparty** ${PROJECT_SOURCE_DIR}/3rdparty/wininclude **${VcpkgRoot}/include**)

**Comment by ras0219-msft** [comment]
Issue is fixed _and_ evpp upgraded to 0.7.0 in Vcpkg master branch

**Comment by tristonl** [comment]
Thank you!
