### ISSUE TITLE
macOS Mojave Build Issues

### ISSUE THREAD

**Issue by npyl** [Qihoo360/evpp#212]
As title says I cannot build on macOS Mojave 10.14.4.
I've followed the getting started guide, installed all required libraries.

It seems though cmake doesn't look for glog and the rest of libraries.

Error message after `make` is:

```SH
/Users/npyl/cpp/download/evpp/evpp/logging.h:9:10: fatal error: 
      'glog/logging.h' file not found
#include <glog/logging.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [evpp/CMakeFiles/evpp_boost.dir/buffer.cc.o] Error 1
make[1]: *** [evpp/CMakeFiles/evpp_boost.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by blueshen** [comment]
include_directories (${PROJECT_SOURCE_DIR}
                         ${PROJECT_SOURCE_DIR}/3rdparty
                         /usr/local/include   # 指向有glog的目录
                        )
    link_directories(/usr/local/lib)   # 指向有dylib的目录

hope this helpful

**Comment by atxsinn3r** [comment]
brew install glog

and add these in your CMakeLists:

find_package(glog)
target_link_libraries(EvppTest glog::glog)

**Comment by denismakogon** [comment]
Greetings. I'm experiencing the same issues, therefore, I can't build a shared library for further usage. On my system, I have both `event2` and `glog` installed via `brew`. Getting started doc says that I need to run `make -j`, in order to run all targets, but that command fails, here' the message:
```
fatal error: 'event2/event.h' file not found
...
fatal error: 'glog/logging.h' file not found
#include <glog/logging.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
1 error generated.
make[2]: *** [evpp/CMakeFiles/evpp_concurrentqueue_static.dir/libevent.cc.o] Error 1
make[1]: *** [evpp/CMakeFiles/evpp_concurrentqueue_static.dir/all] Error 2
make[2]: *** [evpp/CMakeFiles/evpp_concurrentqueue.dir/httpc/conn.cc.o] Error 1
1 error generated.
1 error generated.
make[2]: *** [evpp/CMakeFiles/evpp_boost.dir/httpc/response.cc.o] Error 1
make[1]: *** [evpp/CMakeFiles/evpp_boost.dir/all] Error 2
make[2]: *** [evpp/CMakeFiles/evpp_concurrentqueue.dir/event_loop.cc.o] Error 1
make[1]: *** [evpp/CMakeFiles/evpp_concurrentqueue.dir/all] Error 2
make: *** [all] Error 2
```

so, it says that something I wrong with my libraries, but I can clearly see that they were configured properly:
```
pkg-config --libs libevent
-L/opt/homebrew/Cellar/libevent/2.1.12/lib -levent
```
```
pkg-config --libs libglog 
-L/opt/homebrew/Cellar/glog/0.6.0/lib -lglog
```

So, can you please help?
